DROP TABLE IF EXISTS erp_branch_sales_order;
DROP TABLE IF EXISTS erp_branch_sales_order_items;

CREATE TABLE erp_branch_sales_order (
    so_id INTEGER PRIMARY KEY,
    so_number TEXT,
    company_id INTEGER,
    branch_id INTEGER,
    location_id INTEGER,
    customer_id INTEGER,
    billing_address_id INTEGER,
    billingAddress TEXT,
    shipping_address_id INTEGER,
    shippingAddress TEXT,
    shipToLastInsertedId INTEGER,
    country_id INTEGER,
    kamId INTEGER,
    profit_center TEXT,
    compInvoiceType TEXT,
    goodsType TEXT,
    credit_period INTEGER,
    currency_id INTEGER,
    currency_name TEXT,
    conversion_rate REAL,
    cgst REAL,
    sgst REAL,
    igst REAL,
    taxComponents TEXT,
    totalQty REAL,
    totalItems INTEGER,
    totalDiscount REAL,
    totalCashDiscount REAL,
    totalTax REAL,
    totalAmount REAL,
    round_off REAL,
    ref_no TEXT,
    ref_type TEXT,
    claimz_id INTEGER,
    jobOrderApprovalStatus TEXT,
    approvalStatus TEXT,
    delivery_date TEXT,
    so_date TEXT,
    soPostingTime TEXT,
    validityperiod TEXT,
    remarks TEXT,
    status TEXT,
    created_at TEXT,
    created_by TEXT,
    updated_at TEXT,
    updated_by TEXT,
    bank_id INTEGER,
    placeOfSupply TEXT
);

CREATE TABLE erp_branch_sales_order_items (
    so_item_id INTEGER PRIMARY KEY,
    so_id INTEGER,
    inventory_item_id INTEGER,
    itemCode TEXT,
    itemName TEXT,
    itemDesc TEXT,
    goodsType TEXT,
    hsnCode TEXT,
    uom TEXT,
    qty REAL,
    remainingQty REAL,
    unitPrice REAL,
    itemTargetPrice REAL,
    totalPrice REAL,
    discountVariantId INTEGER,
    cashDiscountType TEXT,
    cashDiscountPercentage REAL,
    cashDiscountAmount REAL,
    itemTotalDiscount REAL,
    totalDiscount REAL,
    totalTax REAL,
    tax TEXT,
    tolerance REAL,
    completion_value REAL,
    invStatus TEXT,
    status TEXT,
    itemRemarks TEXT,
    lineNo INTEGER,
    createdAt TEXT,
    createdBy TEXT,
    updatedAt TEXT,
    updatedBy TEXT,
    FOREIGN KEY (so_id) REFERENCES erp_branch_sales_order(so_id)
);
